cnpg:
  mode: recovery
  instances: 0
  backup:
    enabled: false
    endpointURL: https://sdid-248f-n8n.s3obj.ecs.objstore.r2.pi2.minint.fr
  recovery:
    endpointURL: https://sdid-248f-n8n.s3obj.ecs.objstore.r2.pi2.minint.fr
